menu:
    Blog: /
    Archive: /archives/
#    Weibo: http://weibo.com/1999469107
    GitHub: https://github.com/cgoder
    Golss: http://www.golss.ml
    Taoke: http://www.mlmababa.com
#    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus: cgoder
#duoshuo: cgoder

# Analytics
# google-analytics:
ga: UA-96450309-1

# Copyright Infomation
startyear: 2015
